import type { ModelData } from "./energy-metrics";

// Static catalogue of popular models.  `overall_parameters_in_billions` reflects the
// headline size (all experts included for MoE) while `active_parameters_in_billions`
// is the compute-relevant subset.

export const models: ModelData[] = [
    { "name": "Kimi K2",                                   "overall_parameters_in_billions": 1000, "active_parameters_in_billions": 32 },       /* [1] */
    { "name": "DeepSeek V3 0324",                          "overall_parameters_in_billions": 675,  "active_parameters_in_billions": 37 },       /* [2] */
    { "name": "Nous: Hermes 3 405B Instruct",              "overall_parameters_in_billions": 405,  "active_parameters_in_billions": 405 },
    { "name": "Meta: Llama 3.1 405B (base)",               "overall_parameters_in_billions": 405,  "active_parameters_in_billions": 405 },
    { "name": "Meta: Llama 3.1 405B Instruct",             "overall_parameters_in_billions": 405,  "active_parameters_in_billions": 405 },
    { "name": "NVIDIA: Llama 3.1 Nemotron Ultra 253B v1",  "overall_parameters_in_billions": 253,  "active_parameters_in_billions": 253 },
    { "name": "Qwen: Qwen3 235B A22B Thinking 2507",       "overall_parameters_in_billions": 235,  "active_parameters_in_billions": 22 },       /* [23] */
    { "name": "Qwen: Qwen3 235B A22B Instruct 2507",       "overall_parameters_in_billions": 235,  "active_parameters_in_billions": 22 },       /* [23] */
    { "name": "Qwen: Qwen3 235B A22B",                     "overall_parameters_in_billions": 235,  "active_parameters_in_billions": 22 },       /* [23] */
    { "name": "Goliath 120B",                              "overall_parameters_in_billions": 120,  "active_parameters_in_billions": 120 },
    { "name": "TheDrummer: Anubis Pro 105B V1",            "overall_parameters_in_billions": 105,  "active_parameters_in_billions": 105 },
    { "name": "Meta: Llama 3.2 90B Vision Instruct",       "overall_parameters_in_billions": 90,   "active_parameters_in_billions": 90 },
    { "name": "Qwen: Qwen2.5 VL 72B Instruct",             "overall_parameters_in_billions": 72,   "active_parameters_in_billions": 72 },
    { "name": "Magnum v4 72B",                             "overall_parameters_in_billions": 72,   "active_parameters_in_billions": 72 },
    { "name": "Magnum v2 72B",                             "overall_parameters_in_billions": 72,   "active_parameters_in_billions": 72 },
    { "name": "Qwen2.5 72B Instruct",                      "overall_parameters_in_billions": 72,   "active_parameters_in_billions": 72 },
    { "name": "Qwen 2 72B Instruct",                       "overall_parameters_in_billions": 72,   "active_parameters_in_billions": 72 },
    { "name": "TheDrummer: Anubis 70B V1.1",               "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "Shisa AI: Shisa V2 Llama 3.3 70B",          "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "Typhoon2 70B Instruct",                     "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "DeepSeek: R1 Distill Llama 70B",            "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "Sao10K: Llama 3.3 Euryale 70B",             "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "Meta: Llama 3.3 70B Instruct",              "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "NVIDIA: Llama 3.1 Nemotron 70B Instruct",   "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "Sao10K: Llama 3.1 Euryale 70B v2.2",        "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "Nous: Hermes 3 70B Instruct",               "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "Meta: Llama 3.1 70B Instruct",              "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "Sao10k: Llama 3 Euryale 70B v2.1",          "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "NeverSleep: Llama 3 Lumimaid 70B",          "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "Meta: Llama 3 70B Instruct",                "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "Midnight Rose 70B",                         "overall_parameters_in_billions": 70,   "active_parameters_in_billions": 70 },
    { "name": "TheDrummer: Valkyrie 49B V1",               "overall_parameters_in_billions": 49,   "active_parameters_in_billions": 49 },
    { "name": "NVIDIA: Llama 3.3 Nemotron Super 49B v1",   "overall_parameters_in_billions": 49,   "active_parameters_in_billions": 49 },
    { "name": "Liquid: LFM 40B MoE",                       "overall_parameters_in_billions": 40,   "active_parameters_in_billions": 12 },       /* [39][40] */
    { "name": "TheDrummer: Skyfall 36B V2",                "overall_parameters_in_billions": 36,   "active_parameters_in_billions": 36 },
    { "name": "Z.AI: GLM 4 32B",                           "overall_parameters_in_billions": 32,   "active_parameters_in_billions": 32 },
    { "name": "Qwen: Qwen3 32B",                           "overall_parameters_in_billions": 32,   "active_parameters_in_billions": 32 },
    { "name": "THUDM: GLM Z1 32B",                         "overall_parameters_in_billions": 32,   "active_parameters_in_billions": 32 },
    { "name": "THUDM: GLM 4 32B",                          "overall_parameters_in_billions": 32,   "active_parameters_in_billions": 32 },
    { "name": "ArliAI: QwQ 32B RpR v1",                    "overall_parameters_in_billions": 32,   "active_parameters_in_billions": 32 },
    { "name": "Qwen: Qwen2.5 VL 32B Instruct",             "overall_parameters_in_billions": 32,   "active_parameters_in_billions": 32 },
    { "name": "Qwen: QwQ 32B",                             "overall_parameters_in_billions": 32,   "active_parameters_in_billions": 32 },
    { "name": "DeepSeek: R1 Distill Qwen 32B",             "overall_parameters_in_billions": 32,   "active_parameters_in_billions": 32 },
    { "name": "Qwen: QwQ 32B Preview",                     "overall_parameters_in_billions": 32,   "active_parameters_in_billions": 32 },
    { "name": "Qwen2.5 Coder 32B Instruct",                "overall_parameters_in_billions": 32,   "active_parameters_in_billions": 32 },
    { "name": "Qwen: Qwen3 30B A3B",                       "overall_parameters_in_billions": 30,   "active_parameters_in_billions": 3.3 },      /* [55] */
    { "name": "Google: Gemma 3 27B",                       "overall_parameters_in_billions": 27,   "active_parameters_in_billions": 27 },
    { "name": "Google: Gemma 2 27B",                       "overall_parameters_in_billions": 27,   "active_parameters_in_billions": 27 },
    { "name": "Mistral: Mistral Small 3.2 24B",            "overall_parameters_in_billions": 24,   "active_parameters_in_billions": 24 },
    { "name": "Nous: DeepHermes 3 Mistral 24B Preview",    "overall_parameters_in_billions": 24,   "active_parameters_in_billions": 24 },
    { "name": "Mistral: Mistral Small 3.1 24B",            "overall_parameters_in_billions": 24,   "active_parameters_in_billions": 24 },
    { "name": "Dolphin3.0 R1 Mistral 24B",                 "overall_parameters_in_billions": 24,   "active_parameters_in_billions": 24 },
    { "name": "Noromaid 20B",                              "overall_parameters_in_billions": 20,   "active_parameters_in_billions": 20 },
    { "name": "OpenGVLab: InternVL3 14B",                  "overall_parameters_in_billions": 14,   "active_parameters_in_billions": 14 },
    { "name": "Qwen: Qwen3 14B",                           "overall_parameters_in_billions": 14,   "active_parameters_in_billions": 14 },
    { "name": "Agentica: Deepcoder 14B Preview",           "overall_parameters_in_billions": 14,   "active_parameters_in_billions": 14 },
    { "name": "DeepSeek: R1 Distill Qwen 14B",             "overall_parameters_in_billions": 14,   "active_parameters_in_billions": 14 },
    { "name": "Pygmalion: Mythalion 13B",                  "overall_parameters_in_billions": 13,   "active_parameters_in_billions": 13 },
    { "name": "ReMM SLERP 13B",                            "overall_parameters_in_billions": 13,   "active_parameters_in_billions": 13 },
    { "name": "MythoMax 13B",                              "overall_parameters_in_billions": 13,   "active_parameters_in_billions": 13 },
    { "name": "Meta: Llama Guard 4 12B",                   "overall_parameters_in_billions": 12,   "active_parameters_in_billions": 12 },
    { "name": "Google: Gemma 3 12B",                       "overall_parameters_in_billions": 12,   "active_parameters_in_billions": 12 },
    { "name": "Infermatic: Mistral Nemo Inferor 12B",      "overall_parameters_in_billions": 12,   "active_parameters_in_billions": 12 },
    { "name": "TheDrummer: UnslopNemo 12B",                "overall_parameters_in_billions": 12,   "active_parameters_in_billions": 12 },
    { "name": "TheDrummer: Rocinante 12B",                 "overall_parameters_in_billions": 12,   "active_parameters_in_billions": 12 },
    { "name": "Mistral: Pixtral 12B",                      "overall_parameters_in_billions": 12,   "active_parameters_in_billions": 12 },
    { "name": "Mistral Nemo 12B Celeste",                  "overall_parameters_in_billions": 12,   "active_parameters_in_billions": 12 },
    { "name": "Meta: Llama 3.2 11B Vision Instruct",       "overall_parameters_in_billions": 11,   "active_parameters_in_billions": 11 },
    { "name": "Fimbulvetr 11B v2",                         "overall_parameters_in_billions": 11,   "active_parameters_in_billions": 11 },
    { "name": "THUDM: GLM 4.1V 9B Thinking",               "overall_parameters_in_billions": 9,    "active_parameters_in_billions": 9 },
    { "name": "Google: Gemma 2 9B",                        "overall_parameters_in_billions": 9,    "active_parameters_in_billions": 9 },
    { "name": "DeepSeek: Deepseek R1 0528 Qwen3 8B",       "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "Qwen: Qwen3 8B",                            "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "Llama Guard 3 8B",                          "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "DeepSeek: R1 Distill Llama 8B",             "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "AionLabs: Aion-RP 1.0 (8B)",                "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "Mistral: Ministral 8B",                     "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "Google: Gemini 1.5 Flash 8B",               "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "NeverSleep: Lumimaid v0.2 8B",              "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "Sao10K: Llama 3 8B Lunaris",                "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "Meta: Llama 3.1 8B Instruct",               "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "NousResearch: Hermes 2 Pro - Llama-3 8B",   "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "Meta: LlamaGuard 2 8B",                     "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "Meta: Llama 3 8B Instruct",                 "overall_parameters_in_billions": 8,    "active_parameters_in_billions": 8 },
    { "name": "Bytedance: UI-TARS 7B",                     "overall_parameters_in_billions": 7,    "active_parameters_in_billions": 7 },
    { "name": "DeepSeek: R1 Distill Qwen 7B",              "overall_parameters_in_billions": 7,    "active_parameters_in_billions": 7 },
    { "name": "EleutherAI: Llemma 7b",                     "overall_parameters_in_billions": 7,    "active_parameters_in_billions": 7 },
    { "name": "AlfredPros: CodeLLaMa 7B Instruct Solidity", "overall_parameters_in_billions": 7,   "active_parameters_in_billions": 7 },
    { "name": "Liquid: LFM 7B",                            "overall_parameters_in_billions": 7,    "active_parameters_in_billions": 7 },
    { "name": "Qwen2.5 7B Instruct",                       "overall_parameters_in_billions": 7,    "active_parameters_in_billions": 7 },
    { "name": "Qwen: Qwen2.5-VL 7B Instruct",              "overall_parameters_in_billions": 7,    "active_parameters_in_billions": 7 },
    { "name": "Mistral: Mistral 7B Instruct v0.3",         "overall_parameters_in_billions": 7,    "active_parameters_in_billions": 7 },
    { "name": "Mistral: Mistral 7B Instruct",              "overall_parameters_in_billions": 7,    "active_parameters_in_billions": 7 },
    { "name": "Mistral: Mistral 7B Instruct v0.2",         "overall_parameters_in_billions": 7,    "active_parameters_in_billions": 7 },
    { "name": "Toppy M 7B",                                "overall_parameters_in_billions": 7,    "active_parameters_in_billions": 7 },
    { "name": "Mistral: Mistral 7B Instruct v0.1",         "overall_parameters_in_billions": 7,    "active_parameters_in_billions": 7 },
    { "name": "Google: Gemma 3n 4B",                       "overall_parameters_in_billions": 4,    "active_parameters_in_billions": 4 },
    { "name": "Google: Gemma 3 4B",                        "overall_parameters_in_billions": 4,    "active_parameters_in_billions": 4 },
    { "name": "Liquid: LFM 3B",                            "overall_parameters_in_billions": 3,    "active_parameters_in_billions": 3 },
    { "name": "Mistral: Ministral 3B",                     "overall_parameters_in_billions": 3,    "active_parameters_in_billions": 3 },
    { "name": "Meta: Llama 3.2 3B Instruct",               "overall_parameters_in_billions": 3,    "active_parameters_in_billions": 3 },
    { "name": "DeepSeek: R1 Distill Qwen 1.5B",            "overall_parameters_in_billions": 1.5,  "active_parameters_in_billions": 1.5 },
    { "name": "Meta: Llama 3.2 1B Instruct",               "overall_parameters_in_billions": 1,    "active_parameters_in_billions": 1 }
  ]
  
// Re-export default for convenience so callers can `import models from "@/lib/models"`.
export default models;
  